version: '2'
services:
  l2a:
    build: 
      context: ./dockerfile
    volumes:
    - $archives:/var/sentinel2_data/archives:rw
    - $unzipped_scenes:/var/sentinel2_data/unzipped_scenes
    - ./src:/src:ro
    environment:
    - USERID=1000
    - SEN2COR_HOME=/sen2cor
    - SEN2COR_BIN=/sen2cor
    working_dir: /var/sentinel2_data/unzipped_scenes
